if ! type "$nvim" > /dev/null; then
  export EDITOR='nvim'
  alias vim='nvim'
  alias vi='nvim'
fi

eval "$(starship init zsh)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# gem
export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH

# mise
if command -v mise >/dev/null 2>&1; then
  eval "$(mise activate zsh)"
fi
