# Path to your oh-my-zsh installation.
export ZSH=$HOME/.config/oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(git z nvm rbenv)

source $ZSH/oh-my-zsh.sh

if ! type "$nvim" > /dev/null; then
  export EDITOR='nvim'
  alias vim='nvim'
  alias vi='nvim'
fi

alias tmuxa="tmux attach-session -t"

eval "$(starship init zsh)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# gem
export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH
